export default {
  MAIN: 'main',
  MAIN_TAB: 'main_tab',
  HOME: 'home',
  WALLET: 'wallet',
  LOGIN: 'login',
  NFT: 'NFT',
  RANKING: 'ranking',
  STORE: 'store',
  RUN: 'run',
  PROFILE: 'profile',
  CREATE_WALLET: 'createWallet',
  IMPORT_WALLET: 'importWallet',
  REGISTER: 'register',
  NFT_DETAIL: 'nftDetail',
  TOGGLE_2FA: 'toggle2FA',
  CHANGE_PASSWORD: 'changePassword',
  TRADE: 'trade',
  MY_NFT_DETAIL: 'myNFTDetail',
  FORGOT_PASS: 'forgotPass',
  TRANSFER_EXTERNAL: 'transferExternal',
  TRANSFER_FUNDING: 'transferFunding',
  AFFILIATE: 'affiliate',
};
